apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      name: {{ template "fullname" . }}
    spec:
      containers:
        - image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          name: manager
          args:
            - "-data-dir=/var/lib/cert-manager"
          {{if .Values.staging}}
            - "-acme-url=https://acme-staging.api.letsencrypt.org/directory"
          {{else}}
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
          {{end}}
          env:
            - name: DNSMADEEASY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: api_key
            - name: DNSMADEEASY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: api_secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
        - image: palmstonegames/kubectl-proxy:1.4.0
          name: kubectl
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}
