apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "default"
    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.provisioner}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi