name: nfs-provisioner
home: https://github.com/kubernetes-incubator/nfs-provisioner
version: 1.0.2
description: nfs-provisioner Chart for Kubernetes.
sources:
  - https://github.com/mirusresearch/charts/incubator/nfs-provisioner
maintainers:
  - name: Don Spaulding
    email: don@mirusresearch.com
