name: nfs-provisioner
home: https://github.com/kubernetes-incubator/nfs-provisioner
version: 1.0.1-a
description: nfs-provisioner Chart for Kubernetes.
sources:
  - https://github.com/kubernetes-incubator/nfs-provisioner
maintainers:
  - name: Maxime FRANCK
    email: m@3ko.fr
