apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-ui"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.consul.Component}}"
spec:
  type: "NodePort"
  ports:
  - name: http
    port: 8500
  selector:
    component: "{{.Release.Name}}-{{.Values.consul.Component}}"
