apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-consul-ui"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-consul"
spec:
  ports:
  - name: http
    port: 8500
  selector:
    component: "{{.Release.Name}}-consul"
  type: nodePort
