apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  ports:
    - name: {{.Release.Name}}
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{.Release.Name}}
