apiVersion: v1
kind: Service
metadata:
  name: vault-ui-svc
spec:
  ports:
    - name: vault-ui-http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: vault-ui-deployment
