apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault-deployment
  # namespace: "{{ template "namespace" . }}"
  labels:
    app: {{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-deployment
    spec:
      containers:
      - name: vault
        image: "{{.Values.image}}:{{.Values.imageTag}}"
        imagePullPolicy: {{.Values.imagePullPolicy}}
        command:
          - vault
        args:
          - server
          - -config=/etc/vault/cfg/vault-config.hcl
        ports:
          - name: http
            containerPort: 80
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - name: config
          mountPath: /etc/vault/cfg
        resources:
          limits:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
          requests:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
      volumes:
      - name: config
        configMap:
          name: vault-config
          items:
          - key: vault-config.hcl
            path: vault-config.hcl
