apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data: 
  vault-config.hcl : |
    backend "consul" {
      address = "{{ template "fullname" . }}:8500"
      redirect_addr = "https://{{ .Values.vault.domain }}:80"
      path = "vault"
    }

    cluster_name = "{{ template "fullname" . }}"
    
    listener "tcp" {
      address = "0.0.0.0:80"
      tls_disable = 1
    }
