apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  namespace: "{{ template "namespace" . }}"
spec:
  ports:
    - name: vault-deployment-http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: vault-deployment
