apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
      - name: {{.Release.Name}}
        image: "{{.Values.image}}:{{.Values.imageTag}}"
        imagePullPolicy: {{.Values.imagePullPolicy}}
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/vault/cfg
        env:
        - name: "VAULT_DEBUG"
          value: {{ .Values.debug | quote }}
        resources:
          limits:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
          requests:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
      volumes:
      - name: config
        configMap:
          name: {{.Release.Name}}-config
          items:
          - key: config.json
            path: config.json
