# This file creates the deployment object for the nginx ingress controller
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        name: {{ template "fullname" . }}
        ports:
        - containerPort: 80
        {{ if .Values.local }}
          hostPort: 80
        {{ end }}
        - containerPort: 443
        {{ if .Values.local }}
          hostPort: 443
        {{ end }}
        args:
         - -v=3