{{ if not (.Values.local) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
  labels:
    app: {{ template "fullname" . }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP}}
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  selector:
    app: {{ template "fullname" . }}
{{ end }}
