name: consul
home: https://github.com/hashicorp/consul
icon: https://www.consul.io/assets/images/logo_large-475cebb0.png
version: 0.2.0
description: Hashicorp Consul Helm chart for Kubernetes.
sources:
  - https://github.com/kelseyhightower/consul-on-kubernetes
maintainers:
  - name: Don Spaulding
    email: don@mirusresearch.com
